from __future__ import annotations

from agent_browser_skill.actions_auth import action_clear_session, action_login
from agent_browser_skill.actions_batch import action_batch, action_run, normalize_batch_commands
from agent_browser_skill.actions_generic import (
    action_click,
    action_fill,
    action_open,
    action_screenshot,
    action_skills,
    action_snapshot,
    action_start,
    action_wait,
)
from agent_browser_skill.actions_maintenance import (
    action_cleanup,
    action_close,
    action_profile_aliases,
    action_recover,
    action_set_profile_alias,
    action_status,
)
from agent_browser_skill.actions_manual import (
    action_challenge_detected,
    action_close_manual_access,
    action_continue_after_manual,
    action_desktop_open,
    action_desktop_screenshot,
    action_desktop_snapshot,
    action_downloads,
    action_evaluate,
    action_find_text,
    action_page_markdown,
    action_page_markdown_act,
    action_read_page_md,
    action_click_handle,
    action_fill_handle,
    action_select_handle,
    action_wait_ready,
    action_scroll_until_stable,
    action_get_page_text,
    action_get_title,
    action_extract_links,
    action_extract_blocks,
    action_click_text,
    action_click_selector,
    action_manual_desktop,
    action_navigate_pagination,
    action_read_artifact,
    action_share_session,
    action_smart_read,
    action_stop_desktop,
)
from agent_browser_skill.actions_saby import action_saby_tenders_csv
from agent_browser_skill.actions_artifacts import action_list_artifacts, action_read_artifact_by_id, action_read_artifact_slice, action_search_artifact, action_summarize_artifact
from agent_browser_skill.actions_extractors import (
    action_extract_article, action_extract_table, action_extract_search_results, action_extract_updates_by_date,
    action_extract_forum_posts, action_filter_by_date, action_summarize_posts,
)
from agent_browser_skill.core.output import metadata

ACTIONS = {
    "start": action_start,
    "skills": action_skills,
    "open": action_open,
    "snapshot": action_snapshot,
    "click": action_click,
    "fill": action_fill,
    "type": action_fill,
    "wait": action_wait,
    "screenshot": action_screenshot,
    "share_session": action_share_session,
    "manual_desktop": action_manual_desktop,
    "stop_desktop": action_stop_desktop,
    "close_manual_access": action_close_manual_access,
    "desktop_open": action_desktop_open,
    "desktop_snapshot": action_desktop_snapshot,
    "desktop_screenshot": action_desktop_screenshot,
    "evaluate": action_evaluate,
    "read_artifact": action_read_artifact,
    "read_artifact_by_id": action_read_artifact_by_id,
    "search_artifact": action_search_artifact,
    "read_artifact_slice": action_read_artifact_slice,
    "summarize_artifact": action_summarize_artifact,
    "list_artifacts": action_list_artifacts,
    "smart_read": action_smart_read,
    "find_text": action_find_text,
    "page_markdown": action_page_markdown,
    "page_markdown.get": action_page_markdown,
    "page_markdown.act": action_page_markdown_act,
    "read_page_md": action_read_page_md,
    "click_handle": action_click_handle,
    "fill_handle": action_fill_handle,
    "select_handle": action_select_handle,
    "wait_ready": action_wait_ready,
    "scroll_until_stable": action_scroll_until_stable,
    "get_page_text": action_get_page_text,
    "get_title": action_get_title,
    "extract_links": action_extract_links,
    "extract_blocks": action_extract_blocks,
    "extract_article": action_extract_article,
    "extract_table": action_extract_table,
    "extract_search_results": action_extract_search_results,
    "extract_updates_by_date": action_extract_updates_by_date,
    "extract_forum_posts": action_extract_forum_posts,
    "filter_by_date": action_filter_by_date,
    "summarize_posts": action_summarize_posts,
    "click_text": action_click_text,
    "click_selector": action_click_selector,
    "navigate_pagination": action_navigate_pagination,
    "downloads": action_downloads,
    "saby_tenders_csv": action_saby_tenders_csv,
    "challenge_detected": action_challenge_detected,
    "continue_after_manual": action_continue_after_manual,
    "batch": action_batch,
    "run": action_run,
    "login": action_login,
    "clear_session": action_clear_session,
    "close": action_close,
    "recover": action_recover,
    "status": action_status,
    "profile_aliases": action_profile_aliases,
    "set_profile_alias": action_set_profile_alias,
    "cleanup": action_cleanup,
}
